name: 🐛 Bug Report
description: Create a report to help us improve
title: '[Bug]: '
labels: ['bug', 'needs-triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛

        Before submitting, please check if a similar issue already exists.

  - type: textarea
    id: bug-description
    attributes:
      label: 📝 Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 📷 Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Paste screenshots here or drag and drop images

  - type: dropdown
    id: browsers
    attributes:
      label: 🌐 Browser
      description: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other

  - type: dropdown
    id: device-type
    attributes:
      label: 📱 Device
      description: What device are you using?
      options:
        - Desktop
        - Mobile
        - Tablet

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 Additional context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful

  - type: checkboxes
    id: terms
    attributes:
      label: ✋ Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/yourusername/FlavorPantry/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: I have searched for existing issues before creating this one
          required: true
